#!/bin/bash

# This was brilliantly generated by chatgpt

# URL of the emoji test file
URL="https://unicode.org/Public/emoji/16.0/emoji-test.txt"
FILE="tmp.txt"

# Download the emoji test file
curl -s "$URL" -o "$FILE"

echo "// SPDX-License-Identifier: MIT"
echo
echo "#pragma once"
echo "#include <map>"
echo "#include <string>"
echo
echo "// this file was generated by ./make_emojis_header.sh"
echo "// from " $URL
echo
echo "const std::map<std::string, std::string> emojis = {"

# Process the file and extract fully-qualified emoji with their shortcodes
grep -Eo '^[0-9A-F ]+; fully-qualified +# .+' "$FILE" | while read -r line; do
    # Extract emoji glyph
    emoji=$(echo "$line" | awk -F '#' '{print $2}' | sed -E 's/^ +//g' | cut -d ' ' -f1)
    
    # Extract description and format shortcode
    shortcode=$(echo "$line" | awk -F '#' '{print $2}' | sed -E 's/^ +//g' | cut -d ' ' -f3- |
        sed -E 's/E[0-9]+\.[0-9]+ //g' |  # Remove E<number>.<number>
        sed -E "s/[-:,.&'’]/_/g" |        # Replace '-', ':', ',', "'", '’' with '_'
        tr '[:upper:]' '[:lower:]' |      # Convert to lowercase
        sed -E 'y/àáâäãåçèéêëìíîïñòóôöõùúûüýÿ/aaaaaaceeeeiiiinooooouuuuyy/' | # Remove accents
        sed -E 'y/ÀÁÂÄÃÅÇÈÉÊËÌÍÎÏÑÒÓÔÖÕÙÚÛÜÝŸ/aaaaaaceeeeiiiinooooouuuuyy/' | # Remove accents
        tr ' ' '_' |                       # Replace spaces with '_'
        sed -E 's/_+/_/g')                 # Contract multiple '_' into one

    [[ -n "$shortcode" ]] && echo "    {\"${shortcode}\", \"${emoji}\"},"
done

echo "};"

rm -f "$FILE"
