import json
import emoji

def generate_emoji_list():
    emoji_list = []

    # some manual addings
    emoji_list.append(f'"+1", "👍"')
    emoji_list.append(f'"-1", "👎"')
    emoji_list.append(f'"smile", "🙂"')

    # browse all emojis from the emoji package
    for emoji_char in emoji.EMOJI_DATA.keys():
        # generate pair shortcode / emoji
        shortcode = emoji.demojize(emoji_char).strip(':')        
        emoji_list.append(f'"{shortcode}", "{emoji_char}"')
    return emoji_list

# generate the list
full_emoji_list = generate_emoji_list()

# write header file
print("// SPDX-License-Identifier: MIT")
print()
print("#pragma once")
print("#include <map>")
print("#include <string>")
print()
print("// this file was generated by make_emojis_h_from_python_package.py,")
print("// package installed with 'pip install emoji'")
print()
print("const std::map<std::string, std::string> emojis = {")
for emoji_entry in full_emoji_list:
    print("    {", end="")
    print(emoji_entry, end="")
    print("},")
print("};")
