#!/bin/bash

_remo_completion() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    if [[ ":blush:" == "$cur"* ]]; then
        COMPREPLY+=":blush:"
    fi
}

# complete -F _remo_completion -o default bash
complete -E _remo_completion
