#!/bin/zsh

: "${EMOJI_CLI_FILTER:="fzf-tmux -d 15%:fzf:peco:percol:fzy"}"

available() {
    local x candidates

    # candidates should be list like "a:b:c" concatenated by a colon
    candidates="$1:"

    while [ -n "$candidates" ]; do
        # the first remaining entry
        x=${candidates%%:*}
        # reset candidates
        candidates=${candidates#*:}

        # check if x is available
        if (( $+commands[${x%% *}] )); then
            echo "$x"
            return 0
        else
            continue
        fi
    done

    return 1
}

_remo_completion() {
  local output query

  output=$(emoji-expander -a | eval "$(available "$EMOJI_CLI_FILTER")" | awk '{print $1}')
  [[ -z "$output" ]] && output=":"

  BUFFER=${BUFFER}${output}
  CURSOR=${#BUFFER}
  zle reset-prompt
}

zle -N _remo_completion
bindkey ":" _remo_completion
